Add ---skip-test-db capabilities
bitnami/bitnami-docker-mariadb pull request #237
Opened 2021-05-20 11:08 UTC by sebastienmusso

Description of the change

Add the capability to disable  creation of test database 

Benefits

Users will be able to pass environment variable to disable the creation of test database instead of add post bootstrap scripts

Additional information

Feature available only in version 10.5+

2021-05-21 06:30 UTC, juan131 requested changes
Thanks so much for your PR! Please take a look to my comments that are mostly related to our conventions for the scripts.

2021-05-21 06:30 UTC, juan131 commented on 10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +    fi
Some conventions for the env. variables used in Bitnami scripts:
- Prefix the env. variable with `MARIADB_`: `MARIADB_SKIP_TEST_DB`
- Please declare the env. variable in the [mysq-env.sh](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/mariadb-env.sh)
- Use `yes/no` instead of `true/false` as allowed values.
```suggestion
    if is_boolean_yes "$MARIADB_SKIP_TEST_DB"; then
        args+=("--skip-test-db")
    fi
```
Other suggestions:
- Include this block under the `if [[ "$DB_FLAVOR" = "mariadb" ]]; then` block (line 708)
- You can use the block below to ensure that it's only executed if MariaDB is `10.5` or higher:
```bash
        if "$(mysql_get_version)" =~ ^10.[01234]. ]]; then
        (...)
        fi
```

2021-05-21 07:43 UTC, sebastienmusso commented on 10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +    fi
Hi, I made fix on my environment,

Does all this changes have to be made in all files (mysql-env.sh and libmariadb.sh) of all folder version of mariadb (folder 10.2/10.3...) because this feature should only be available in mariadb 10.5+ ?

2021-05-21 09:25 UTC, sebastienmusso commented
convention have been added in dbb8801

2021-05-21 10:31 UTC, juan131 commented on 10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +    fi
Yes @sebastienmusso
Please replicate the changes on every branch. You're right and it doesn't make sense to add a feature on branch `10.1` that's only available on `10.5` but our internal pipeline has a unique source of truth for this `libmariadb.sh` and, therefore, we need to replicate it.

2021-05-21 12:02 UTC, sebastienmusso commented
convention have been added in all other mariadb version in f7b8838 commit

regards

2021-05-24 07:20 UTC, juan131 approved these changes
Approving your changes! I'll send your code for internal review and keep you updated.

2021-05-24 09:50 UTC, sebastienmusso commented
> Approving your changes! I'll send your code for internal review and keep you updated.

Thanks for your help and all your work on this great provider which help us a lot.

Regards

2021-05-24 11:41 UTC, merged

2021-05-24 11:43 UTC, juan131 commented
Your changes were approved/merged.

What's next? A new revision of the MariaDB container (`10.5.10-debian-10-r15`) will be released within the next hours including your changes.

Thanks again for the contribution!