Allow any password for container users (+ misc other fixes)
bitnami/bitnami-docker-mariadb pull request #257
Opened 2021-11-24 00:14 UTC by grooverdan

**Description of the change**

This allows users to choose any password, quotes, any language, backslashes even new lines.

Removes special handling of mysql.user view that isn't needed any more.

**Benefits**

Users will have less problems with passwords that are not accepted.

**Possible drawbacks**

Users may need to appreciate that the complex password they set needs to be handled correctly in all other contexts correctly.

**Applicable issues**

- #204
- #250 (partial)

**Additional information**

Remove the limitation on backslash_password_error to allow all passwords
to be used. The ways this is achieved is:
* adding the function mysql_sql_escape_string_literal which escapes $1
  as if this is ending up inside a single quoted string literal.
* using --binary-mode on mysql to ensure that any use characters are
  used as is
* Removing NO_BACKSLASH_ESCAPES from the sql_mode (for the session). This is the default
  but for any reason a user may have it in their configuration file.
* Passing the password to mysql using the env variable $MYSQL_PWD
  so that its tolerant of the ambiguities of command line parsing of
  complex strings.
* mysql_upgrade was started using --skip-grant-tables. This should
  help address #250, but there was an underlying problem about passing
  the env $MYSQL_PWD through that I didn't get to the bottom of.

Closes #204

Other fixes included because they would massively conflict:

* Remove "FLUSH PRIVILEGES". This is never needed on any user
  modification SQL. Its only needed if underlying tables are changed.
* ${password:+identied by $password} bash syntax used rather than
  subshell. This triggered the shellcheck (hence
https://github.com/koalaman/shellcheck/issues/2383) and the exemption.
* Remove MariaDB mysql.user alter view code. Per docs
  (https://mariadb.com/kb/en/mysqluser-table/) from 10.4.13 there is
  a mariadb.sys user that owns this table. Even if upgrading from
  a datadir before this, the mysql_upgrade will change the owner
  of this view. So nothing special is needed any more.
* shellcheck disable=SC2153 on line 28 for $DB_EXTRA_FLAGS

Tests:

$ podman run --rm --name bnmariadb10.6 -e MARIADB_REPLICATION_MODE=master -e MARIADB_REPLICATION_USER=smith -e MARIADB_REPLICATION_PASSWORD=$'a\\ b" c' -e MARIADB_ROOT_PASSWORD=$'a\n \' \nb' -e MARIADB_USER=sandy -e MARIADB_PASSWORD=$'\n\'\\aa-\x09-zz"_%\n' -e BITNAMI_DEBUG=true   bitnami:10.6

$ podman exec --env MYSQL_PWD=$'a\\ b" c' bnmariadb10.6   mysql -u smith -e 'select current_user(); show grants;'
current_user()
smith@%
Grants for smith@%
GRANT REPLICATION SLAVE ON *.* TO `smith`@`%` IDENTIFIED BY PASSWORD '*E378A1747A212A634186FAA24EBA4C84243B42EC' WITH GRANT OPTION

$ podman exec --env MYSQL_PWD=$'a\n \' \nb'  bnmariadb10.6   mysql -u root -e 'select current_user(); show grants;'
current_user()
root@%
Grants for root@%
GRANT ALL PRIVILEGES ON *.* TO `root`@`%` IDENTIFIED BY PASSWORD '*357E0D70A4E9EAA7D30B087BBA4A4A34F060ECB2' WITH GRANT OPTION

$ podman exec --env MYSQL_PWD=$'\n\'\\aa-\x09-zz"_%\n'   bnmariadb10.6   mysql -u sandy -e 'select current_user(); show grants;'
current_user()
sandy@%
Grants for sandy@%
GRANT USAGE ON *.* TO `sandy`@`%` IDENTIFIED BY PASSWORD '*845F5E8EBBFF983DE9BA0857D2C662B8E0BA5A19'

2021-11-24 14:08 UTC, migruiz4 requested changes
Hi @grooverdan, thank you very much for your contribution!

Your changes look good to me except for one small comment you can see below.
We are also testing these changes in our internal pipeline, so I will let you know if anything comes up.

2021-11-30 16:47 UTC, migruiz4 requested changes
Hi @grooverdan,

Apparently, the `MYSQL_PWD` being in the wrong line was not trivial and causes MariaDB to fail. I added some comments below with my findings while testing the changes.

- Fixed an issue with `mysql_execute` and `--binary-mode`, where 'binary-mode' would sometimes be interpreted as the password (third argument of the function) and not an extra arg for the MySQL binary.
- The `flush privileges` are not trivial and should not be removed. Running MySQL commands with 'root' password will fail although the password should have been updated.
- The option `--skip-grant-tables` is ignored if MySQL is already running. This is the case when MySQL first initializes, causing it to fail.

Please review the changes as we can not accept this PR in its current status.

2021-11-30 16:47 UTC, migruiz4 commented on 10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +        mysql_execute "mysql" "root" --binary-mode <<EOF
```suggestion
        mysql_execute "mysql" "root" "" "--binary-mode" <<EOF
```

2021-11-30 16:47 UTC, migruiz4 commented on 10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> -flush privileges;
Removing  `flush privileges;` causes the changes to root password to not be applied, leading to issues while running `mysql_ensure_user_not_exists()`.

In the issue description you mention it not being needed, but in my tests it shows that behavior is not the same if applied or not.

2021-11-30 16:47 UTC, migruiz4 commented on 10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> -flush privileges;
Same as above, I don't think we should remove `flush privileges;`.

2021-11-30 16:47 UTC, migruiz4 commented on 10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +        mysql_start_bg --skip-grant-tables
`--skip-grant-tables` will be ignored if mysql is already running, as it happens during the first execution where MySQL starts in the background in line 243, causing MySQL to fail.

2021-11-30 20:44 UTC, grooverdan commented on 10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh
> +        mysql_execute "mysql" "root" --binary-mode <<EOF
of course. Thanks.

2021-12-01 04:03 UTC, grooverdan commented
Left FLUSH PRIVILEGES in, but changed its position. There was a gap.

2021-12-09 16:32 UTC, javsalgar commented
Currently @migruiz4 is on PTO. As soon as he comes back he will provide more feedback on the PR.

2021-12-30 01:24 UTC, closed without merging